apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n5ujtq7sq-nodejs
  janus-idp.io/tekton: n5ujtq7sq-nodejs
  backstage.io/kubernetes-id: n5ujtq7sq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n5ujtq7sq-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
